#!/bin/bash

BASEDIR=$(dirname $0)
ITERATIONS="-n 5"
WORKLOAD="-s default"

mkdir -p output

for bench in `cat ${BASEDIR}/../config/bench.txt`
do
    ${BASEDIR}/run $1 "-cp $2:${BASEDIR}/../lib/callback.jar Harness ${bench} ${WORKLOAD} ${ITERATIONS} -c ch.usi.dag.callback.ProfilerCallback" 2>&1 | tee output/${bench}.log
    mv *.gz output/
done

