#!/bin/bash

BASEDIR=$(dirname $0)
INSTRUMENTATION_LIB=$1
shift

$DISL_HOME/bin/disl.py -d $DISL_HOME/output/ -cs -i=${INSTRUMENTATION_LIB} \
    -c_opts="-XX:-BootstrapJVMCI -XX:+TieredCompilation" \
    -c_opts="-G:+UseGraalInstrumentation -G:-RemoveNeverExecutedCode" \
    -c_opts="-G:-InlineDuringParsing -G:SmallCompiledLowLevelGraphSize=0" \
    -c_app="$@" \
    -s_exclusionlist=${BASEDIR}/../config/excl.lst

