#!/bin/bash

mx vm -Xbootclasspath/a:../lib/graal-query.jar -G:-RemoveNeverExecutedCode -G:-InlineDuringParsing \
    -cp ../lib/junit-4.11.jar:../lib/hamcrest-core-1.3.jar:bin \
    org.junit.runner.JUnitCore $@
